### ISSUE TITLE
Невозможно выбрать и изменить размер области аватара при его загрузке. 

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#1]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. На странице “Моя страница” нажать кнопку “Редактировать” под аватаром; 
3. Выбрать “Загрузить фото” (или “Выбрать фото из галереи”;
4. Рядом со старым аватаром появляется загруженная (или выбранная) картинка, на которой обозначена область будущего аватара.

![default](https://cloud.githubusercontent.com/assets/23305911/23938702/74aa61d8-096e-11e7-8569-ea77fb6c7dab.jpg)

_Фактический результат:_
Невозможно изменить и перенести область, обозначающую на картинке будущий аватар. 

_Ожидаемый результат:_
Область для выбора аватара можно изменить (размер и выбранную область на загруженной/выбранной картинке).

**Comment by estpitt** [comment]
Отложить.
