### ISSUE TITLE
Отсутствуют гиперссылки на словах “доход” и “потенциальный” во всплывающем окне уведомлений “Финансы”.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#10]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Открыть уведомление “Финансы” в верхнем тулбаре;
3. Навести курсор мыши на слово “доход”/”потенциальный доход” и кликнуть.

![default](https://cloud.githubusercontent.com/assets/23305911/23943720/7c10aca8-0981-11e7-9243-f0ca26a1db0e.jpg)
![default](https://cloud.githubusercontent.com/assets/23305911/23943727/7e1a8262-0981-11e7-9f20-db8bcf453c40.jpg)

_Фактический результат:_
Ничего не происходит.

_Ожидаемый результат:_
Перенаправление на страницу “Финансы” (вкладка “Основное”), где показывается доход или потенциальный доход.

**Comment by estpitt** [comment]
В работу
