### ISSUE TITLE
Поле сообщения на странице “Обратной связи” имеет возможность ручного изменения высоты и ширины окна.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#11]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу “Обратная связь”;
3. Курсором мыши “захватить” нижний правый угол поля сообщения и оттащить вправо.

![default](https://cloud.githubusercontent.com/assets/23305911/23943913/1150dc3e-0982-11e7-9c9e-a2c4cf435ca2.jpg)

_Фактический результат:_
Окно сообщения растягивается и выходит за рамки центральной части интерфейса.

_Ожидаемый результат:_
Размер окна сообщения не изменяется в ручном режиме.

**Comment by estpitt** [comment]
В работу
