### ISSUE TITLE
На странице “Обратной связи” при количестве текста, превышающем высоту окна, появляется полоса прокрутки.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#12]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу “Обратная связь”;
3. Набрать текст в окне сообщения (использовать перенос строки несколько раз).

_Фактический результат:_
Появляется полоса прокрутки. Верхние строчки текста исчезают из поля видимости при дальнейшем наборе.

![default](https://cloud.githubusercontent.com/assets/23305911/23944187/fb7ad878-0982-11e7-9666-15766f19fa01.jpg)

_Ожидаемый результат:_
Высота окна для ввода сообщения увеличивается автоматически. Текст не исчезает из поля видимости.

**Comment by estpitt** [comment]
В работу
