### ISSUE TITLE
Некорректно отцентрованы блоки с видеофайлами на страницах “Партнерам” и “О клубе”.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#13]
_Как воспроизвести:_
1. Открыть страницу https://www.discounter-club.ru;
2. Перейти на страницу “О клубе”;
3. Нажать на левую кнопку “Видео”;

![default](https://cloud.githubusercontent.com/assets/23305911/23944280/4e646cde-0983-11e7-97c6-5051ac729df0.jpg)

4. Закрыть окно видео;
5. Нажать на правую кнопку “Видео”;

![2](https://cloud.githubusercontent.com/assets/23305911/23944301/697e613c-0983-11e7-8379-4de092fdda9a.jpg)

6. Закрыть окно видео;
7. Перейти на страницу “Партнерам”;
8. Нажать на кнопку “Видео”;

![default](https://cloud.githubusercontent.com/assets/23305911/23944335/8a812824-0983-11e7-87e6-b96e25f2d0ad.jpg)

_Фактический результат:_
Серая подложка видео отцентрована, а видео смещено вправо. 

_Ожидаемый результат:_
Подложка и видео отцентрованы.

**Comment by estpitt** [comment]
В работу
