### ISSUE TITLE
Меняется размер footer’а в зависимости от количества партнеров на странице www.discounter-club.ru/accounts/aboutpartners/ после фильтрации и поиска.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#14]
_Как воспроизвести:_
1. Открыть страницу https://www.discounter-club.ru;
2. Перейти на страницу “О клубе”;
3. Перейти на страницу “Наши партнеры”;
4. Отфильтровать партнеров (в “Фильтр по городам” ввести “Москва”, в категориях выбрать “Бары/Ночные клубы”);

![1](https://cloud.githubusercontent.com/assets/23305911/23944462/fa19dece-0983-11e7-89c3-639f0fd4dba9.jpg)

5. Отфильтровать партнеров (в “Фильтр по городам” ввести “Москва”, в категориях выбрать “Аксессуары”);

![2](https://cloud.githubusercontent.com/assets/23305911/23944471/04ff87bc-0984-11e7-908a-69e8fc56cff4.jpg)

6. Отфильтровать партнеров (в “Фильтр по городам” ввести “Москва”, в категориях выбрать “Цветы/Флористика”);

![3](https://cloud.githubusercontent.com/assets/23305911/23944483/0f589ca8-0984-11e7-80c5-13c7bdc50f06.jpg)

_Фактический результат:_
Размер footer’а меняется в зависимости от того, сколько результатов поиска выдает сервис. 

_Ожидаемый результат:_
Размер footer’а закреплен и остается неизменным.

**Comment by estpitt** [comment]
В работу
