### ISSUE TITLE
При попытке поделиться информацией о фотоконкурсе через социальные сети генерируется некорректная ссылка.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#15]
_Как воспроизвести:_

1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу “Фотоконкурс”;
3. Открыть конкурс (например, фотоконкурс "Жизнь в движении");
4. Рассказать о новости через социальную сеть ВКонтакте;
5. Открыть страницу Вконтакте;
6. Открыть сообщение и перейти по ссылке.

_Фактический результат:_
Пользователь попадает на страницу “Новости” (если он авторизован на сервисе “Дискаунтер”) или на стартовую страницу (если не авторизован).

_Ожидаемый результат:_
Пользователь попадает на страницу конкурса.

**Comment by VeronikaDed** [comment]
Причина бага:
Ссылка на конкурс www.discounter-club.ru/competitions/113
Ссылка, которая приходит пользователю www.discounter-club.ru/competition/113

**Comment by estpitt** [comment]
В работу
