### ISSUE TITLE
Не отображается статус других участников.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#17]
Как воспроизвести:
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу “Моя страница”;
3. Выбрать “Подписчики” на “Моя страница”;
4. Выбрать одного из подписчиков в появившемся окне (Перейти на страницу одного из подписчиков).

_Фактический результат:_
На странице подписчика в правом верхнем углу статус не отображается.

![default](https://cloud.githubusercontent.com/assets/23305911/23946866/3fc33ce6-098d-11e7-92b2-a54109d9d364.jpg)

_Ожидаемый результат:_
Также как и на странице самого пользователя на странице подписчика в правом верхнем углу должен отображаться статус.

**Comment by estpitt** [comment]
В работу
