### ISSUE TITLE
При вставке адреса email из буфера обмена или выборе из запомненных адресов при авторизации не отрабатывает скрипт уменьшения placeholder.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#2]
_Как воспроизвести:_
1. Открыть страницу www.discounter-club.ru;
2. Нажать кнопку “Вход”;
3. В поле “Электронная почта” выбрать из запомненных адресов email или вставить адрес из буфера обмена.

![placeholder](https://cloud.githubusercontent.com/assets/23305911/23938816/e93ed042-096e-11e7-8f1d-1d8222311623.jpg)

_Фактический результат:_ 
В поле “Электронная почта” происходит перекрытие шрифтов вводимого текста и названия поля.

_Ожидаемый результат:_ 
В поле “Электронная почта” размер шрифта названия поля уменьшается или пропадает при введении текста.

**Comment by estpitt** [comment]
В работу.
