### ISSUE TITLE
При открытии модального окна партнера через гиперссылку на странице “Новости” пользователя перенаправляет на страницу “Партнеры”. 

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#22]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Выбрать новость и кликнуть на гиперссылку.

_Фактический результат:_ 
Открывается модальное окно с информацией о партнере. Происходит переход на страницу “Партнеры”. При закрытии модального окна пользователь оказывается на странице “Партнеры”. 

_Ожидаемый результат:_
Открывается модальное окно с информацией о партнере.  При закрытии модального окна пользователь остается на странице “Новости”.

**Comment by estpitt** [comment]
В работу.
