### ISSUE TITLE
Email-адрес компании на странице “Контакты” отображается как простой текст.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#23]
_Как воспроизвести:_
1. Открыть страницу www.discounter-club.ru;
2. Перейти на страницу “Контакты”.

_Фактический результат:_
Email-адрес отображается как простой текст.

![mailto](https://cloud.githubusercontent.com/assets/23305911/23947260/072fa1c4-098f-11e7-9fa6-156dfdf6d47d.jpg)

_Ожидаемый результат:_
Email отображается как ссылка с атрибутом mailto.

**Comment by estpitt** [comment]
В работу
