### ISSUE TITLE
В браузере Microsoft Edge иконка “лайк” под фотографиями отображается не целиком.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#25]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Открыть страницу “Мои фотографии”;
3. Открыть любую фотографию.

_Фактический результат:_
Иконка “лайк” отображается не целиком.

![default](https://cloud.githubusercontent.com/assets/23305911/23947436/d5b17cca-098f-11e7-9c93-681e73e36f54.jpg)

Ожидаемый результат: 
Иконка отображается корректно.

**Comment by estpitt** [comment]
В работу.
