### ISSUE TITLE
На странице другого пользователя, если у него нет ни одного подписчика, при нажатии на раздел "Подписчики" открывается пустое модальное окно.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#26]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу “Подписчики”;
3. Выбрать одного из подписчиков (у которого нет подписчиков) и перейти на его страницу;
4. Нажать на раздел "Подписчики" под аватаром.

_Фактический результат:_
Открывается пустое модальное окно.

![default](https://cloud.githubusercontent.com/assets/23305911/23947650/b3c4931c-0990-11e7-8af6-d04e7716e416.jpg)

_Ожидаемый результат:_
Открываемое модальное окно должно иметь ту же структуру, как и у самого пользователя, который не имеет (рисунок 1) или имеет подписчиков (рисунок 2). 

![2](https://cloud.githubusercontent.com/assets/23305911/23947898/b12d0f52-0991-11e7-9018-c41b3545406c.jpg)

![default](https://cloud.githubusercontent.com/assets/23305911/23947687/e60aeda8-0990-11e7-8258-d2eee14a767d.jpg)

**Comment by estpitt** [comment]
В работу.
