### ISSUE TITLE
Кнопка "Вход" на стартовой странице

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#27]
Стоит перенести кнопку "Вход" в центр стартовой страницы. Например, так: 
![2017-03-14_19-06-46](https://cloud.githubusercontent.com/assets/23305911/23953963/1546d364-09a7-11e7-8c0a-2ed02c45610a.jpg)

**Comment by estpitt** [comment]
В работу, но с дополнениями. В данном случаем сделано правильно иначе будем сбивать с толку пользователя, так как люди будут хотеть ввести код и нажать на кнопку вход. 

Кнопка вход в данном случае вход в ЛК. Поэтому нужно сделать как на картинке ниже.

![image](https://cloud.githubusercontent.com/assets/26965136/24759423/08dc1550-1aee-11e7-9fab-d77d05ccdcf7.png)
