### ISSUE TITLE
При прокрутке страницы "Наши партнеры" отсутствует кнопка "Наверх" 

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#28]
На странице “Наши партнеры” (https://www.discounter-club.ru/accounts/aboutpartners/) при прокрутке страницы вниз отсутствует кнопка для возвращения пользователя к началу страницы “Наверх” (рис.1), как это сделано на странице "Партнеры" для авторизованных пользователей (рис.2).  

Рисунок 1
![default](https://cloud.githubusercontent.com/assets/23305911/23954438/58572626-09a8-11e7-9dcf-b2afc2ca6264.jpg)

Рисунок 2
![default](https://cloud.githubusercontent.com/assets/23305911/23954633/e2d23ba6-09a8-11e7-9d1e-6394a011dfe9.jpg)

**Comment by estpitt** [comment]
В работу
