### ISSUE TITLE
Две кнопки "Редактировать" на странице пользователя

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#29]
Достаточно одной кнопки “Редактировать”, поскольку они ведут на одну и ту же страницу “Настройки - Профиль”. Стоит оставить ту, что располагается под аватаром пользователя.

![2](https://cloud.githubusercontent.com/assets/23305911/23954893/7c60532a-09a9-11e7-88e8-f7e2a3740067.jpg)

**Comment by estpitt** [comment]
В работу. 

![image](https://cloud.githubusercontent.com/assets/26965136/24759092/098acfd8-1aed-11e7-979e-e9b6806e6f03.png)
