### ISSUE TITLE
При смене пароля не проходит проверка на совпадение с действующим.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#3]
_Как воспроизвести:_
1. Открыть страницу www.discounter-club.ru;
2. Перейти на страницу “Настройки”;
3. Открыть вкладку “Безопасность”;
4. Выбрать “Сменить пароль”;
5. Ввести действующий пароль в поле “Текущий пароль”;
6. Ввести такой же пароль в полях “Новый пароль” и “Подтвердить пароль”.

_Фактический результат:_ 
Появляется сообщение об успешной смене пароля и пользователя перенаправляет на стартовую страницу сервиса, где ему необходимо вновь авторизоваться. 

_Ожидаемый результат:_
Появляется сообщение о совпадении старого и нового пароля и просьба изменить новый пароль.

**Comment by estpitt** [comment]
В работу
