### ISSUE TITLE
Модальное окно авторизации закрывает логотип сервиса.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#35]
При нажатии на кнопку “Вход” появляется окно, которое закрывает название сервиса. Логотип стоит перенести выше или окно сделать чуть ниже.

![placeholder](https://cloud.githubusercontent.com/assets/23305911/23956111/d7bd952c-09ac-11e7-9594-f11718ab31a9.jpg)

**Comment by estpitt** [comment]
В работу. 

![image](https://cloud.githubusercontent.com/assets/26965136/24755399/be756170-1ae2-11e7-8974-326b623dfa17.png)
