### ISSUE TITLE
Централизация полей ввода и кнопок на стартовых страницах сервиса.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#37]
Поле ввода кода, надпись “Неверный код приглашения” и кнопку “Зарегистрироваться” необходимо перенести в центр страницы, данные сегменты должны идти друг под другом (не выступать вправо и влево) на одинаковом расстоянии.
 
![default](https://cloud.githubusercontent.com/assets/23305911/23956969/30415f9c-09af-11e7-84b6-5aa6fd9a2c5e.jpg)
Голубым прямоугольником отмечена область, где должны располагаться кнопки и основные поля ввода. Красными прямоугольниками обозначены поля, которые необходимо сдвинуть, стрелки - направления.
Тот же принцип должен быть сохранен и тут:

![default](https://cloud.githubusercontent.com/assets/23305911/23956984/42c11266-09af-11e7-90ad-1975fe8498d5.jpg)

**Comment by estpitt** [comment]
В работу.

![image](https://cloud.githubusercontent.com/assets/26965136/24755205/f27e1b98-1ae1-11e7-95b5-65303bb4688f.png)
