### ISSUE TITLE
На странице подтверждения адреса почтового ящика после его изменения email отображается как ссылка с атрибутом mailto.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#4]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу “Настройки”;
3. Открыть вкладку “Безопасность”;
4. Выбрать “Сменить email”;
5. Подтвердить смену email в почтовом ящике, открыв ссылку.

![mailto](https://cloud.githubusercontent.com/assets/23305911/23940360/a25cb570-0975-11e7-92a4-fad7856e0e9e.jpg)

_Фактический результат:_
На странице подтверждения email-адрес указан в формате ссылки с атрибутом mailto.

_Ожидаемый результат:_
Подтверждаемый email-адрес имеет формат обычного текста.

**Comment by estpitt** [comment]
Отклонить. Не влияет на совершаемое итоговое действие.
