### ISSUE TITLE
Единое разрешение для страниц с логотипом

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#41]
На стартовых страницах сервиса (до авторизации) разное разрешение. Привычнее, когда оно не меняется.
![2](https://cloud.githubusercontent.com/assets/23305911/23957365/3b7f1dc6-09b0-11e7-8894-2d3931c2a621.jpg)
![default](https://cloud.githubusercontent.com/assets/23305911/23957364/3b7c259e-09b0-11e7-9d0b-67f9b0bf598d.jpg)

**Comment by estpitt** [comment]
В работу. За основу берём размер лого на главной.
