### ISSUE TITLE
Расположение модальных окон.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#42]
Все модальные окна должны быть выровнены по центру экрана или хотя бы располагаться ниже уровня тулбара.
![4](https://cloud.githubusercontent.com/assets/23305911/23957467/7f992bb4-09b0-11e7-89e7-6b9c2c8ab924.jpg)
![1](https://cloud.githubusercontent.com/assets/23305911/23957465/7f94f422-09b0-11e7-9998-6c9c29948aaa.jpg)
![2](https://cloud.githubusercontent.com/assets/23305911/23957466/7f97f654-09b0-11e7-91fc-98b04122b3de.jpg)
![3](https://cloud.githubusercontent.com/assets/23305911/23957464/7f93000e-09b0-11e7-9559-a584e9012bfb.jpg)

**Comment by estpitt** [comment]
В работу. По центру.

Но по хорошему в процессе переделки интерфейса от них стоит отказаться вообще.
