### ISSUE TITLE
Отсутствует возможность форматирования текста на странице “Обратная связь”.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#45]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу "Обратная связь". 

_Фактический результат:_ 
Возможность редактировать текст отсутствует. 

_Ожидаемый результат:_
Согласно документации (стр. 44 Приложения №1 к Договору №1204 от «23» июня 2016 г.), форма обратной связи имеет возможность редактирования (выбор шрифта, размера текста).

**Comment by estpitt** [comment]
В работу.
