### ISSUE TITLE
Не работает счетчик “лайков” под фотографиями пользователей.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#5]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу “Мои фотографии”;
3. Выбрать фотографию;
4. Нажать на кнопку “лайк” (сердечко).

_Фактический результат:_
Счетчик "лайков" остается с прежним показателем.

_Ожидаемый результат:_
Счетчик "лайков" должен обновиться.

**Comment by estpitt** [comment]
Нельзя лайкать свои фотографии.
