### ISSUE TITLE
Отсутствует сообщение об ошибке авторизации при введении незарегистрированного email.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#6]
_Как воспроизвести:_
1. Открыть страницу www.discounter-club.ru;
2. Нажать кнопку “Вход”;
3. Ввести некорректный email (незарегистрированный в сервисе);
4. Ввести пароль;
5. Нажать кнопку “Войти”.

_Фактический результат:_
Страница не обновляется. Сообщений об ошибке не возникает. 

_Ожидаемый результат:_
Перенаправление на страницу ошибки авторизации или появление под полем введения email текста ошибки “Нет пользователя с таким email”.

**Comment by estpitt** [comment]
Исправлено уже.
