### ISSUE TITLE
Не работает вызов программы Skype при выборе соответствующего поля в разделе “Контакты” на “Моей странице”

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#7]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу “Моя страница”;
3. “Показать подробную информацию”;
4. Перейти к разделу “Контакты”;
5. Щелкнуть по никнейму пользователя в поле Skype.

![skype](https://cloud.githubusercontent.com/assets/23305911/23943175/9649d68c-097f-11e7-97c3-8df17dd45b8b.jpg)

_Фактический результат:_
Страница остается неизменной. Приложение Skype не запускается.

_Ожидаемый результат:_
Клик по никнейму пользователя вызывает приложение Skype.

**Comment by estpitt** [comment]
В работу
