### ISSUE TITLE
Пользователя перенаправляет в начало страницы "Партнеры" при закрытии модального окна с информацией о партнере, если в нем были просмотрены еще какие-либо вкладки помимо "Общая информация".

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#8]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Перейти на страницу “Партнеры”;
3. Пролистать страницу вниз;
4. Открыть одного из партнеров;
5. Посмотреть в открывшемся модальном окне вкладку “Общая информация”, не открывая другие;
6. Закрыть модальное окно;

_Промежуточный результат:_ 
Пользователь остается на прежнем месте в списке партнеров. 

7. Открыть одного из партнеров;
8. В открывшемся модальном окне перейти во вкладку “Регионы присутствия”, “Адреса партнеров” или “На карте”;
9. Закрыть модальное окно.

_Фактический результат:_
Пользователь оказывается в начале страницы “Партнеры”.

_Ожидаемый результат:_
Пользователь остается на прежнем месте в списке партнеров.

**Comment by estpitt** [comment]
В работу
