### ISSUE TITLE
Цвет ссылки “Закрыть” во всплывающем окне уведомлений “Финансы” не соответствует общему дизайну.

### ISSUE THREAD

**Issue by VeronikaDed** [VeronikaDed/Discounter#9]
_Как воспроизвести:_
1. Открыть и авторизоваться на странице www.discounter-club.ru;
2. Открыть уведомление “Финансы” в верхнем тулбаре;
3. Навести курсор мыши на гиперссылку “Закрыть”.

![default](https://cloud.githubusercontent.com/assets/23305911/23943518/cac52dca-0980-11e7-9664-25578ee8f6a1.jpg)

_Фактический результат:_
Ссылка “Закрыть” окрашивается в синий цвет.

_Ожидаемый результат:_
Ссылка “Закрыть”  при наведении курсора мыши окрашивается в оранжевый цвет, согласно общему стилю сервиса.

**Comment by estpitt** [comment]
В работу
